Strona ASP.Net MVC/CarLotMVC/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using AutoLotDAL;

namespace CarLotMVC.Controllers
{
    public class InventoryController : Controller
    {
        private CarLot db = new CarLot();

        // GET: Inventory
        public ActionResult Index()
        {
            return View(db.Inventory.ToList());
        }

        // GET: Inventory/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventory.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // GET: Inventory/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inventory/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Make,Color,CarNickName")] Inventory inventory)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Inventory inventory1 = new Inventory();
                    await inventory1.AddAsync( inventory.Make, inventory.Color, inventory.CarNickName);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Unable to create record: {ex.Message}");
                return View(inventory);
            }
            return View(inventory);
        }

        // GET: Inventory/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventory.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventory/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< ActionResult> Edit([Bind(Include = "CarId,Make,Color,CarNickName")] Inventory inventory)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(inventory).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                return View(inventory);
            }catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Unable to save record" + ex.Message );
            }
            return View(inventory);
        }

        // GET: Inventory/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inventory inventory = db.Inventory.Find(id);
            if (inventory == null)
            {
                return HttpNotFound();
            }
            return View(inventory);
        }

        // POST: Inventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
           return await Task.Run(()=>
                {
                Inventory inventory = db.Inventory.Find(id);
                db.Inventory.Remove(inventory);
                db.SaveChanges();
                return RedirectToAction("Index");
            });
         }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Strona ASP.Net MVC/CarLotMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index")"><span><img src="~/Picture/toyota.png" width="100px" hight="70px"/></span></a> 
            </div>
            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Home")</li>
                    <li>@Html.ActionLink("Twój garaż", "Index", "Inventory")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Multimedia", "Multimedia", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>

            </div>

        </div>

    </div>
    <div class="jumbotron" style="background-color:grey">
        <h1 style="text-align:center; color:aliceblue;">Witamy na stronie Super Cars <img src="~/Picture/car.gif" width="20%" height="10%" style="border-radius: 50%;" /></h1>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Systemy Rozproszone Adam Górski i Wojciech Stysiek  </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>